/* ═══════════════════════════════════════════════════════════════
   gnoke-worker.js — v1.0.1
   SharedWorker kernel for the Gnoke Trio.
   ───────────────────────────────────────────────────────────────
   Edmund Sparrow © 2026 — MIT License
   Part of the Gnoke Suite

   This file is the "motherboard." It hosts GnokeDB, GnokeBridge,
   and GnokeSync inside a single SharedWorker. All app tabs connect
   as thin clients via gnoke-client.js. There is one RAM mirror,
   one write queue, one sync loop — across every open tab.

   HOW TO LOAD:
     In each app tab:
       const worker = new SharedWorker('/gnoke-worker.js');

     Or use gnoke-client.js (recommended) which wraps this entirely.

   MESSAGE PROTOCOL (client → worker):
     Every message sent to the worker has the shape:
       { _id: string, cmd: string, ...args }

     _id is a unique request ID generated by the client. The worker
     echoes it back in the response so the client can resolve the
     correct Promise. This is the request/response wiring.

   COMMANDS (client → worker):
     OPEN    { _id, cmd:'OPEN' }
     SAVE    { _id, cmd:'SAVE',   collection, payload }
     UPDATE  { _id, cmd:'UPDATE', collection, id, payload }
     REMOVE  { _id, cmd:'REMOVE', collection, id }
     QUERY   { _id, cmd:'QUERY',  collection, filter? }
     PENDING { _id, cmd:'PENDING', collection? }
     SYNC    { _id, cmd:'SYNC' }
     PULL    { _id, cmd:'PULL' }

   RESPONSES (worker → client):
     { _id, ok: true,  result }   — success
     { _id, ok: false, error }    — failure

   BROADCASTS (worker → ALL connected clients, no _id):
     { broadcast: 'STATE_UPDATED', collection, op, record }
       Emitted after every confirmed DB write (save/update/remove).
       All tabs receive this and can re-query or update local UI state.

     { broadcast: 'SYNC_STATUS', pending }
       Emitted after each push() cycle completes.

     { broadcast: 'MASTER_UPDATE', entity, items }
       Emitted after pull() receives a master list overwrite.

   STARTUP SEQUENCE:
     1. First tab connects → worker boots → calls GnokeDB.open()
        (this prompts the folder picker in that tab via the port)
     2. GnokeDB.open() resolves → RAM mirror is live
     3. All subsequent OPEN commands from other tabs resolve instantly
        (GnokeDB._ready is already true)

   IMPORTANT — SharedWorker lifetime:
     The worker stays alive as long as at least one tab has a live
     port. When the last tab closes, the worker is terminated. On
     next open, GnokeDB.open() runs again (wake path — no folder
     picker, just permission re-check and RAM boot from disk).

   DEPENDENCIES:
     gnoke-db.js     — must be importScripts'd before this file's logic
     gnoke-bridge.js — same
     gnoke-sync.js   — same
     All three must expose their globals on `self` (not `window`).
═══════════════════════════════════════════════════════════════ */

// ── Import the Trio ──────────────────────────────────────────
// Paths are relative to the worker file's location.
// Adjust if your directory structure differs.
importScripts(
  './gnoke-db.js',
  './gnoke-bridge.js',
  './gnoke-sync.js'
);

/* ════════════════════════════════════════════════════════════
   WORKER STATE
════════════════════════════════════════════════════════════ */

// All connected tab ports. Used for broadcasting.
const _ports = new Set();

// Boot state. GnokeDB.open() is async and only runs once.
// Subsequent OPEN commands wait on this same promise.
let _bootPromise  = null;
let _booted       = false;
let _folderName   = 'ready'; // set after GnokeDB.open() resolves

/* ════════════════════════════════════════════════════════════
   ENTRY — onconnect
   Fires once per tab that creates a SharedWorker connection.
════════════════════════════════════════════════════════════ */

self.onconnect = function (e) {
  const port = e.ports[0];
  _ports.add(port);

  port.onmessage = (evt) => _handleMessage(port, evt.data);

  // Remove port from broadcast list when the tab closes.
  // SharedWorker ports don't fire a 'close' event reliably across
  // all browsers, but postMessage to a closed port throws — _broadcast
  // catches and cleans up at that point instead.
  port.start();
};

/* ════════════════════════════════════════════════════════════
   MESSAGE ROUTER
════════════════════════════════════════════════════════════ */

async function _handleMessage(port, msg) {
  const { _id, cmd } = msg;

  // Every command needs _id for response routing.
  if (!_id || !cmd) return;

  try {
    switch (cmd) {

      case 'OPEN':
        await _boot();
        _reply(port, _id, { folder: _folderName });
        break;

      case 'SAVE': {
        await _assertBooted();
        const id = await GnokeDB.save(msg.collection, msg.payload);
        _reply(port, _id, { id });
        // Broadcast after reply — client gets its answer first,
        // then all tabs (including the caller) get the state update.
        _broadcast({
          broadcast  : 'STATE_UPDATED',
          collection : msg.collection,
          op         : 'save',
          id,
          record     : msg.payload,
        });
        break;
      }

      case 'UPDATE': {
        await _assertBooted();
        await GnokeDB.update(msg.collection, msg.id, msg.payload);
        _reply(port, _id, { id: msg.id });
        _broadcast({
          broadcast  : 'STATE_UPDATED',
          collection : msg.collection,
          op         : 'update',
          id         : msg.id,
          record     : msg.payload,
        });
        break;
      }

      case 'REMOVE': {
        await _assertBooted();
        await GnokeDB.remove(msg.collection, msg.id);
        _reply(port, _id, { id: msg.id });
        _broadcast({
          broadcast  : 'STATE_UPDATED',
          collection : msg.collection,
          op         : 'remove',
          id         : msg.id,
        });
        break;
      }

      case 'QUERY': {
        await _assertBooted();
        // filter is a serialized function string from the client.
        // We reconstruct it here. This is safe because the worker
        // is a trusted first-party file — no external input reaches
        // this eval path. If you prefer, omit filter support and
        // always return full collections (clients filter locally).
        let filterFn;
        if (msg.filter) {
          try { filterFn = new Function('rec', `return (${msg.filter})(rec)`); }
          catch { filterFn = undefined; }
        }
        const results = await GnokeDB.query(msg.collection, filterFn);
        _reply(port, _id, { results });
        break;
      }

      case 'PENDING': {
        await _assertBooted();
        const hasPending = GnokeDB.hasPendingWrites(msg.collection);
        _reply(port, _id, { hasPending });
        break;
      }

      case 'SYNC': {
        await _assertBooted();
        const syncResult = await GnokeBridge.forceSync();
        _reply(port, _id, syncResult || { ok: true });
        _broadcast({ broadcast: 'SYNC_STATUS', pending: GnokeBridge.getPending().length });
        break;
      }

      case 'PULL': {
        await _assertBooted();
        const pullResult = await GnokeBridge.forcePull();
        _reply(port, _id, pullResult || { ok: true });
        break;
      }

      default:
        _reply(port, _id, null, `Unknown command: ${cmd}`);
    }
  } catch (err) {
    _reply(port, _id, null, err?.message || String(err));
  }
}

/* ════════════════════════════════════════════════════════════
   BOOT — runs once, all subsequent calls wait on the same promise
════════════════════════════════════════════════════════════ */

function _boot() {
  if (_bootPromise) return _bootPromise;

  _bootPromise = (async () => {
    // Wire Bridge to DB — Bridge's onWrite hook fires into DB writes,
    // Bridge's onSyncEvent hook fires into Sync receives.
    // GnokeSync.init() is called by Bridge internally via the hook.
    GnokeBridge.init({
      db  : GnokeDB,
      sync: GNOKE_SYNC,
    });

    // Wire DB compaction and observability hooks.
    GnokeDB.configure({
      onCompact: ({ collection, recordCount, previousLineCount }) => {
        console.log(`[gnoke-worker] compacted ${collection}: ${previousLineCount} → ${recordCount} lines`);
      },
      onReady: () => {
        _booted = true;
      },
    });

    // open() is the blocking boot step — folder picker or wake path.
    // In a SharedWorker, the folder picker dialog is owned by the
    // browser and associated with the tab that triggered this call.
    // Subsequent tabs that send OPEN find _booted=true and return instantly.
    const { folder } = await GnokeDB.open();
    _folderName = folder || 'ready';
    _booted = true;
  })();

  return _bootPromise;
}

function _assertBooted() {
  if (_booted) return Promise.resolve();
  return _boot();
}

/* ════════════════════════════════════════════════════════════
   MESSAGING HELPERS
════════════════════════════════════════════════════════════ */

// Reply to a specific port with a request/response envelope.
function _reply(port, _id, result, error) {
  try {
    if (error) {
      port.postMessage({ _id, ok: false, error });
    } else {
      port.postMessage({ _id, ok: true, result });
    }
  } catch {
    // Port closed — remove it from the broadcast set.
    _ports.delete(port);
  }
}

// Broadcast to every connected port.
// Stale ports (closed tabs) are pruned on send failure.
function _broadcast(msg) {
  for (const port of _ports) {
    try {
      port.postMessage(msg);
    } catch {
      _ports.delete(port);
    }
  }
}



